blank_issues_enabled: true
contact_links:
  - name: Feature request
    url: https://discord.gg/mEDvg6sYp2
    about: Please submit your ideas and requests on the Discord rather than opening an issue
